-- Create notifications table
create table notifications (
    id bigint primary key generated by default as identity,
    type text not null check (type in ('Medicine', 'Exercise', 'Activity', 'Social')),
    message text not null,
    details text,
    priority text not null check (priority in ('high', 'medium', 'low')),
    scheduled_time timestamptz not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    user_id uuid references auth.users(id),
    completed boolean default false
);
